# MarkPresent Configuration - Academic Style
# Clean, professional for academic presentations

theme: solarized
font:
  family: Source Sans Pro
  size: 20

slide_number:
  enabled: true
  format: current/total
  position: bottom-center

navigation:
  enabled: true
  show_arrows: true
  show_dots: false       # No dots for cleaner look
  show_progress: true
  keyboard_shortcuts: true

style:
  shadows: false
  rounded_corners: false
  animations: false      # Conservative for academic setting
  slide_padding: 3rem

logo:
  source: university_logo.png
  location: bottom-left
  size: 100

content:
  title_slide: true
  thank_you_slide: false