# Advanced Features Configuration
# Showcases all new features in Bodh

theme: metropolis

font:
  family: "Fira Sans"
  size: 20

logo:
  source: "examples/sample-logo.svg"
  location: "top-right"
  size: 80

slide_number:
  enabled: true
  format: "current/total"
  position: "bottom-right"

navigation:
  enabled: true
  show_arrows: true
  show_dots: false  # Minimal navigation for Metropolis
  show_progress: true
  keyboard_shortcuts: true

style:
  slide_padding: "3rem 4rem"
  element_margin: "1.5rem"
  shadows: false
  rounded_corners: false
  animations: true
  
  # HR rules under titles
  hrule:
    enabled: true
    width: "70%"
    thickness: "3px"
    style: "solid"
    color: "accent"
  
  # Custom arrow bullets
  bullets:
    style: "arrow"
    color: "secondary"
    size: "1.2em"

layout:
  columns: 2
  column_gap: "3rem"
  alignment: "left"

overlays:
  enabled: true
  transition: "fade"
  duration: "0.4s"

output:
  format: "pdf"
  page_size: "A4"
  orientation: "landscape"

content:
  slide_separator: "---"
  title_slide: true
  thank_you_slide: false