theme:
  name: "gradient"

# Logo configuration
logo:
  path: "examples/sample-logo.svg"
  position: "bottom-left" 
  size: "large"

# Slide numbers
slide_number:
  enabled: true
  format: "{current}/{total}"
  position: "top-left"

# Stylish typography
font:
  family: "Inter"
  size: 16

# Playwright backend
pdf:
  engine: "playwright"

# Math rendering
math:
  enabled: true
  engine: "mathjax"

# Gradient color scheme
colors:
  background: "#667eea"
  text: "#ffffff"
  accent: "#f093fb"

# Clean navigation - only arrows and slide numbers
navigation:
  enabled: true
  show_arrows: true
  show_dots: false
  show_progress: false
  keyboard_shortcuts: true
