theme:
  name: "modern"

# Logo configuration
logo:
  path: "examples/sample-logo.svg"
  position: "bottom-right" 
  size: "small"

# Slide numbers
slide_number:
  enabled: true
  format: "{current}/{total}"
  position: "top-right"

# Modern typography
font:
  family: "Inter"
  size: 18

# Playwright backend
pdf:
  engine: "playwright"

# Math rendering
math:
  enabled: true
  engine: "mathjax"

# Modern color scheme
colors:
  background: "#ffffff"
  text: "#2d3748"
  accent: "#2563eb"