# Bodh Configuration - HR Rule Title Underlines Demo
# Demonstrates HR rules under titles

theme: minimal

font:
  family: "Inter"
  size: 22

style:
  shadows: false
  rounded_corners: false
  animations: true
  slide_padding: "3rem 4rem"
  
  # Enable HR rules for title underlines
  hrule:
    enabled: true
    width: "80%"        # 80% width line under titles
    thickness: "3px"    # Thick line
    style: "solid"      # Solid line style
    color: "accent"     # Use accent color

navigation:
  enabled: true
  show_arrows: true
  show_dots: true
  show_progress: true

slide_number:
  enabled: true
  format: "current/total"
  position: "bottom-right"

content:
  slide_separator: "---"
  title_slide: true
  thank_you_slide: true