theme:
  name: "modern"
  
pdf:
  engine: "latex"              # Use LaTeX instead of Playwright+MathJax
  latex_engine: "pdflatex"     # or xelatex, lualatex
  latex_passes: 2              # Number of compilation passes
  prefer_latex_for_math: true  # Always use LaTeX when math detected

math:
  enabled: true
  engine: "latex"              # Use LaTeX for math rendering in PDF
  # Note: HTML will still use MathJax, only PDF uses LaTeX

slide_number:
  enabled: true
  format: "{current}/{total}"
  position: "bottom-right"

navigation:
  enabled: false               # PDF doesn't need navigation
  
font:
  family: "Inter"
  size: 20

# Performance optimized - should be ~47x faster than MathJax approach