# Bodh Configuration - Logo Demonstration
# Shows logo placement and slide numbering options

theme: modern
font:
  family: Inter
  size: 20

slide_number:
  enabled: true
  format: current/total    # "1/10" format
  position: bottom-right

navigation:
  enabled: true
  show_arrows: true
  show_dots: true
  show_progress: true
  keyboard_shortcuts: true

style:
  shadows: true
  rounded_corners: true
  animations: true
  slide_padding: 2rem

logo:
  source: examples/sample-logo.svg
  location: top-right
  size: 100

content:
  slide_separator: "---"
  title_slide: true
  thank_you_slide: true