theme:
  name: "modern"
  
math:
  enabled: true
  mode: "fast"            # Use fast mock MathJax for testing
  timeout: 1000           # Very short timeout
  fallback: "disabled"    # No fallback needed for testing

slide_number:
  enabled: true
  format: "{current}/{total}"
  position: "bottom-right"

navigation:
  enabled: false          # PDF doesn't need navigation
  
font:
  family: "Inter"
  size: 20