# Math Demo Configuration
# Demonstrates LaTeX mathematics support

theme: minimal

font:
  family: "Computer Modern"
  size: 20

math:
  enabled: true
  engine: "mathjax"
  inline_delimiters: [["$", "$"], ["\\(", "\\)"]]
  display_delimiters: [["$$", "$$"], ["\\[", "\\]"]]

style:
  slide_padding: "3rem 4rem"
  element_margin: "2rem"
  shadows: false
  rounded_corners: false
  animations: true

navigation:
  enabled: true
  show_arrows: true
  show_dots: true
  show_progress: true

slide_number:
  enabled: true
  format: "current/total"
  position: "bottom-right"

output:
  format: "pdf"
  page_size: "A4"
  orientation: "landscape"