# Multi-Column Layout Demo Configuration
# Demonstrates 2 and 3 column layouts

theme: modern

font:
  family: "Inter"
  size: 18

layout:
  columns: 2
  column_gap: "2.5rem"
  alignment: "left"

style:
  slide_padding: "2rem 3rem"
  element_margin: "1rem"
  shadows: true
  rounded_corners: true
  
  bullets:
    style: "circle"
    color: "primary"
    size: "1em"

navigation:
  enabled: true
  show_arrows: true
  show_dots: true
  show_progress: false

slide_number:
  enabled: true
  format: "current"
  position: "bottom-center"