# MarkPresent Configuration - Corporate Presentation
# Professional style with full navigation

theme: dark
font:
  family: Roboto
  size: 22

slide_number:
  enabled: true
  format: current/total   # Show "1/10" format
  position: bottom-right

navigation:
  enabled: true
  show_arrows: true
  show_dots: true
  show_progress: true
  keyboard_shortcuts: true

style:
  shadows: true
  rounded_corners: true
  animations: true
  slide_padding: 3rem

logo:
  source: logo.png      # Company logo
  location: top-right
  size: 120

content:
  title_slide: true
  thank_you_slide: true