# Bodh Configuration - Slide Numbering Variations
# Demonstrates different slide number formats

theme: gradient
font:
  family: Roboto
  size: 22

slide_number:
  enabled: true
  format: percent         # Shows "45%" completion
  position: bottom-center

navigation:
  enabled: true
  show_arrows: true
  show_dots: false        # Clean look with just arrows
  show_progress: true
  keyboard_shortcuts: true

style:
  shadows: true
  rounded_corners: true
  animations: true
  slide_padding: 3rem

logo:
  source: examples/sample-logo.svg
  location: bottom-left
  size: 80

content:
  slide_separator: "---"
  title_slide: true
  thank_you_slide: true